'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\u\tra\kk23\")>  _
    Public Property ParDirSalida() As String
        Get
            Return CType(Me("ParDirSalida"),String)
        End Get
        Set
            Me("ParDirSalida") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ZZ-Pat\TPot\")>  _
    Public Property ParDirPB() As String
        Get
            Return CType(Me("ParDirPB"),String)
        End Get
        Set
            Me("ParDirPB") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ZZ-Pat\tmp\")>  _
    Public Property ParDirTemporal() As String
        Get
            Return CType(Me("ParDirTemporal"),String)
        End Get
        Set
            Me("ParDirTemporal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\u\tra\excel\Planificacion_10.xls")>  _
    Public Property ParArchivoEXCEL() As String
        Get
            Return CType(Me("ParArchivoEXCEL"),String)
        End Get
        Set
            Me("ParArchivoEXCEL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SELECT [ProMss] FROM [Hoja1$] where ProIBM='{0}' and  Idioma='{1}'")>  _
    Public Property ParSQL() As String
        Get
            Return CType(Me("ParSQL"),String)
        End Get
        Set
            Me("ParSQL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("213.97.57.158")>  _
    Public Property ParHostUDP() As String
        Get
            Return CType(Me("ParHostUDP"),String)
        End Get
        Set
            Me("ParHostUDP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("50505")>  _
    Public Property ParPuertoUDP() As Long
        Get
            Return CType(Me("ParPuertoUDP"),Long)
        End Get
        Set
            Me("ParPuertoUDP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ParRecopilarUso() As Boolean
        Get
            Return CType(Me("ParRecopilarUso"),Boolean)
        End Get
        Set
            Me("ParRecopilarUso") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("21")>  _
    Public Property ParIVA() As Single
        Get
            Return CType(Me("ParIVA"),Single)
        End Get
        Set
            Me("ParIVA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("19")>  _
    Public Property ParIRPF() As Single
        Get
            Return CType(Me("ParIRPF"),Single)
        End Get
        Set
            Me("ParIRPF") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MSS")>  _
    Public Property ParProveedor() As String
        Get
            Return CType(Me("ParProveedor"),String)
        End Get
        Set
            Me("ParProveedor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ParMasDeUnPB() As Boolean
        Get
            Return CType(Me("ParMasDeUnPB"),Boolean)
        End Get
        Set
            Me("ParMasDeUnPB") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0.033")>  _
    Public Property ParTarifaPredeterminada() As Single
        Get
            Return CType(Me("ParTarifaPredeterminada"),Single)
        End Get
        Set
            Me("ParTarifaPredeterminada") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ManoloEscobar")>  _
    Public Property ParSecreto() As String
        Get
            Return CType(Me("ParSecreto"),String)
        End Get
        Set
            Me("ParSecreto") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ZZ_PatV01.MySettings
            Get
                Return Global.ZZ_PatV01.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
